sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

language: go
go:
  - "1.12"

before_install:
  - docker --version

install: skip

cache:
  - directories:
      - $GOPATH/pkg

env:
  - GO111MODULE=on

jobs:
  include:
    - name: Blackbox Tests
      script: ./scripts/runBlackboxTests.sh
