FROM golang:1.12.9-alpine3.9

ADD scripts/wait-for.sh /wait-for.sh

RUN apk --update --no-cache add git openssh mongodb gcc cyrus-sasl cyrus-sasl-dev musl-dev && \
    mkdir -p /oplogtoredis && \
    go get github.com/pilu/fresh

WORKDIR /oplogtoredis

CMD fresh
mongo "$OTR_MONGO_URL" --eval 'rs.initiate({ _id: "myapp", members: [{ _id: 0, host: "mongo:27017"}] })'

