version: "3"
services:
  oplogtoredis:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - mongo
      - redis
    command:
      - while :; do :; done & kill -STOP $! && wait $!
#       - mongo:27017
#       - '--'
#       - /wait-for.sh
#       - redis:6379
#       - '--'
#       - sh
#       - -c
#       - |
#         mongo "$$OTR_MONGO_URL" --eval 'rs.initiate({ _id: "myapp", members: [{ _id: 0, host: "mongo:27017"}] })'
#         fresh -c scripts/fresh-runner.conf
    environment:
      - OTR_MONGO_URL=mongodb://mongo/dev
      - OTR_REDIS_URL=redis://master.zhiyan-oplogtoredis-trial.hwnkit.use1.cache.amazonaws.com:6379
      - OTR_LOG_DEBUG=true
    ports:
      - 9000:9000
    volumes:
      - ./scripts/wait-for.sh:/wait-for.sh
      - .:/oplogtoredis
  mongo:
    image: mongo:3.6.2
    command: "mongod --replSet myapp --port 27017"
    logging:
      driver: none
    volumes:
      - './.data/mongo-data:/data/db'
  redis:
    image: redis:3.2.11
    logging:
      driver: none
